### ISSUE TITLE
Cannot install vext.gi in python3.8

### ISSUE THREAD

**Issue by stdedos** [stuaxo/vext#99]
```console
$ file $(which python3); python3 --version;
/usr/bin/python3: symbolic link to python3.8
Python 3.8.10
$ lsb_release -rd
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
$ (.venv) pip list | grep pip
pip              25.0.1
```

```console
$ (.venv) pip install -r requirements.txt
Collecting git+https://github.com/vext-python/vext (from -r requirements.txt (line 4))
  Cloning https://github.com/vext-python/vext to /tmp/pip-req-build-rfe10nc0
  Running command git clone --filter=blob:none --quiet https://github.com/vext-python/vext /tmp/pip-req-build-rfe10nc0
  Resolved https://github.com/vext-python/vext to commit 32ad4d1c5f45797e244df1d2816f76b60f28e20e
  Preparing metadata (setup.py) ... done
Collecting ewmh (from -r requirements.txt (line 1))
  Using cached ewmh-0.1.6-py3-none-any.whl
Collecting vext.gi (from -r requirements.txt (line 5))
  Using cached vext.gi-0.7.4.tar.gz (2.9 kB)
  Preparing metadata (setup.py) ... done
Collecting python-xlib (from ewmh->-r requirements.txt (line 1))
  Using cached python_xlib-0.33-py2.py3-none-any.whl.metadata (6.2 kB)
Collecting ruamel.yaml>=0.11.10 (from vext==0.7.6->-r requirements.txt (line 4))
  Using cached ruamel.yaml-0.18.10-py3-none-any.whl.metadata (23 kB)
Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml>=0.11.10->vext==0.7.6->-r requirements.txt (line 4))
  Using cached ruamel.yaml.clib-0.2.8-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl.metadata (2.2 kB)
Collecting six>=1.10.0 (from python-xlib->ewmh->-r requirements.txt (line 1))
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached ruamel.yaml-0.18.10-py3-none-any.whl (117 kB)
Using cached python_xlib-0.33-py2.py3-none-any.whl (182 kB)
Using cached ruamel.yaml.clib-0.2.8-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (596 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: vext, vext.gi
  Building wheel for vext (setup.py) ... done
  Created wheel for vext: filename=vext-0.7.6-py3-none-any.whl size=14029 sha256=9e8134e87b3f3ac29bfc24d1a9fc9736d2b38a1faa3d24600b65e1305cdb6ce1
  Stored in directory: /tmp/pip-ephem-wheel-cache-h2whl06r/wheels/81/95/cb/da0f1f738dd05f01607c311c82c8b2b55874eb4ede9b546dc0
  Building wheel for vext.gi (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [46 lines of output]
      /home/stdedos/Documents/WorkBulk/Ubuntu/projects/auto-arrange/.venv/lib/python3.8/site-packages/setuptools/__init__.py:94: _DeprecatedInstaller: setuptools.installer and fetch_build_eggs are deprecated.
      !!
      
              ********************************************************************************
              Requirements should be satisfied by a PEP 517 installer.
              If you are using pip, you can try `pip install --use-pep517`.
              ********************************************************************************
      
      !!
        dist.fetch_build_eggs(dist.setup_requires)
      running bdist_wheel
      running build
      /home/stdedos/Documents/WorkBulk/Ubuntu/projects/auto-arrange/.venv/lib/python3.8/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWarning: setup.py install is deprecated.
      !!
      
              ********************************************************************************
              Please avoid running ``setup.py`` directly.
              Instead, use pypa/build, pypa/installer or other
              standards-based tools.
      
              See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
              ********************************************************************************
      
      !!
        self.initialize_options()
      installing to build/bdist.linux-x86_64/wheel
      running install
      vext.gi Install
      running install_data
      creating build/bdist.linux-x86_64/wheel/vext_gi-0.7.4.data/data
      creating build/bdist.linux-x86_64/wheel/vext_gi-0.7.4.data/data/share/vext/specs
      copying gi.vext -> build/bdist.linux-x86_64/wheel/vext_gi-0.7.4.data/data/share/vext/specs
      running install_egg_info
      running egg_info
      writing vext.gi.egg-info/PKG-INFO
      writing dependency_links to vext.gi.egg-info/dependency_links.txt
      writing requirements to vext.gi.egg-info/requires.txt
      writing top-level names to vext.gi.egg-info/top_level.txt
      reading manifest file 'vext.gi.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.txt'
      writing manifest file 'vext.gi.egg-info/SOURCES.txt'
      Copying vext.gi.egg-info to build/bdist.linux-x86_64/wheel/./vext.gi-0.7.4-py3.8.egg-info
      running install_scripts
      Install vext files:
      error: [Errno 2] No such file or directory: 'vext'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vext.gi
  Running setup.py clean for vext.gi
Successfully built vext
Failed to build vext.gi
ERROR: Failed to build installable wheels for some pyproject.toml based projects (vext.gi)
```

```console
$ (.venv) pip install -r requirements.txt --use-pep517
Collecting git+https://github.com/vext-python/vext (from -r requirements.txt (line 4))
  Cloning https://github.com/vext-python/vext to /tmp/pip-req-build-gtrlsxye
  Running command git clone --filter=blob:none --quiet https://github.com/vext-python/vext /tmp/pip-req-build-gtrlsxye
  Resolved https://github.com/vext-python/vext to commit 32ad4d1c5f45797e244df1d2816f76b60f28e20e
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Collecting ewmh (from -r requirements.txt (line 1))
  Using cached ewmh-0.1.6-py3-none-any.whl
Collecting vext.gi (from -r requirements.txt (line 5))
  Using cached vext.gi-0.7.4.tar.gz (2.9 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting python-xlib (from ewmh->-r requirements.txt (line 1))
  Using cached python_xlib-0.33-py2.py3-none-any.whl.metadata (6.2 kB)
Collecting ruamel.yaml>=0.11.10 (from vext==0.7.6->-r requirements.txt (line 4))
  Using cached ruamel.yaml-0.18.10-py3-none-any.whl.metadata (23 kB)
Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml>=0.11.10->vext==0.7.6->-r requirements.txt (line 4))
  Using cached ruamel.yaml.clib-0.2.8-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl.metadata (2.2 kB)
Collecting six>=1.10.0 (from python-xlib->ewmh->-r requirements.txt (line 1))
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached ruamel.yaml-0.18.10-py3-none-any.whl (117 kB)
Using cached python_xlib-0.33-py2.py3-none-any.whl (182 kB)
Using cached ruamel.yaml.clib-0.2.8-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (596 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Building wheels for collected packages: vext, vext.gi
  Building wheel for vext (pyproject.toml) ... done
  Created wheel for vext: filename=vext-0.7.6-py3-none-any.whl size=14025 sha256=6d51f390db6be2918534bc225e0120621c0b469553cccce18369fca20bc2c1f4
  Stored in directory: /tmp/pip-ephem-wheel-cache-959t5bqa/wheels/81/95/cb/da0f1f738dd05f01607c311c82c8b2b55874eb4ede9b546dc0
  Building wheel for vext.gi (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for vext.gi (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      running bdist_wheel
      running build
      installing to build/bdist.linux-x86_64/wheel
      running install
      vext.gi Install
      running install_data
      creating build/bdist.linux-x86_64/wheel/vext_gi-0.7.4.data/data
      creating build/bdist.linux-x86_64/wheel/vext_gi-0.7.4.data/data/share/vext/specs
      copying gi.vext -> build/bdist.linux-x86_64/wheel/vext_gi-0.7.4.data/data/share/vext/specs
      running install_egg_info
      running egg_info
      writing vext.gi.egg-info/PKG-INFO
      writing dependency_links to vext.gi.egg-info/dependency_links.txt
      writing requirements to vext.gi.egg-info/requires.txt
      writing top-level names to vext.gi.egg-info/top_level.txt
      reading manifest file 'vext.gi.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      warning: no files found matching '*.txt'
      writing manifest file 'vext.gi.egg-info/SOURCES.txt'
      Copying vext.gi.egg-info to build/bdist.linux-x86_64/wheel/./vext.gi-0.7.4-py3.8.egg-info
      running install_scripts
      Install vext files:
      error: [Errno 2] No such file or directory: 'vext'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for vext.gi
Successfully built vext
Failed to build vext.gi
ERROR: Failed to build installable wheels for some pyproject.toml based projects (vext.gi)
```

```console
$ (.venv) pip install vext.gi
Collecting vext.gi
  Using cached vext.gi-0.7.4.tar.gz (2.9 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [23 lines of output]
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 14, in <module>
        File "/home/stdedos/Documents/WorkBulk/Ubuntu/projects/auto-arrange/.venv/lib/python3.8/site-packages/setuptools/__init__.py", line 27, in <module>
          from .dist import Distribution
        File "<frozen importlib._bootstrap>", line 991, in _find_and_load
        File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
        File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
        File "/home/stdedos/Documents/WorkBulk/Ubuntu/projects/auto-arrange/.venv/lib/python3.8/site-packages/_virtualenv.py", line 91, in exec_module
          old(module)
        File "/home/stdedos/Documents/WorkBulk/Ubuntu/projects/auto-arrange/.venv/lib/python3.8/site-packages/setuptools/dist.py", line 30, in <module>
          from . import (
        File "/home/stdedos/Documents/WorkBulk/Ubuntu/projects/auto-arrange/.venv/lib/python3.8/site-packages/setuptools/_entry_points.py", line 6, in <module>
          from jaraco.text import yield_lines
        File "/home/stdedos/Documents/WorkBulk/Ubuntu/projects/auto-arrange/.venv/lib/python3.8/site-packages/setuptools/_vendor/jaraco/text/__init__.py", line 12, in <module>
          from jaraco.context import ExceptionTrap
        File "/home/stdedos/Documents/WorkBulk/Ubuntu/projects/auto-arrange/.venv/lib/python3.8/site-packages/setuptools/_vendor/jaraco/context.py", line 17, in <module>
          from backports import tarfile
        File "/home/stdedos/Documents/WorkBulk/Ubuntu/projects/auto-arrange/.venv/lib/python3.8/site-packages/setuptools/_vendor/backports/__init__.py", line 1, in <module>
          __path__ = __import__('pkgutil').extend_path(__path__, __name__)  # type: ignore
        File "/usr/lib/python3.8/pkgutil.py", line 564, in extend_path
          spec = finder.find_spec(final_name)
      TypeError: find_spec() missing 1 required positional argument: 'path'
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

-----

Installation works on Python3.9, but according to https://github.com/vext-python/vext/issues/77#issuecomment-1156230665:
> vext relies on the version of python in the environment being the same as that in the virtual environment, can you run

I am assuming by that you mean: The Python version of the venv MUST BE the same as the Python version `apt install python3-gi` is targeted at.

This should have a check - but idk if it is possible to figure that out. Figuring out the `/usr/bin/python3` target, and comparing it against the current runner?

**Comment by stuaxo** [comment]
It's tricky:   In a virtualenv, we can check which system python the virtualenv uses, and from there we can see if a module is available (e.g. so you can `import gi`).

So all we know at that stage is: can we import it or not.

If we can't then we it would take a some further check of the system to check if it's:

i) not installed at all
ii) installed but, for some other python version.

**Comment by stdedos** [comment]
Ik that py3.8 is EOL (2024-10-07), but _teeeeechnically_ it is still the Python of the Ubuntu 20.04 (... although this is EOL too by now. I am just waiting for the laptop update).

Anyhow - this is _mostly_ for posterity. ... I would've used it if I could though, instead of the "hacky" `ln -s` - if I could.

**Comment by stuaxo** [comment]
As long as you have a pygobject installed in your system python 3.8, then make a virtualenv from it - vext.gi should work there.

Things get a bit funny, because we are doing weird/wrong(?) things with the virtualenv.

Try manually installing vext, then vext.gi:

```sh
pip install vext
pip install vext.gi
```

**Comment by stdedos** [comment]
That does help with the installation indeed. ... However, it's not importable 😕 

```console
p$ (master *) virtualenv venv-vext
created virtual environment CPython3.8.10.final.0-64 in 100ms
  creator CPython3Posix(dest=p/venv-vext, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=~/.local/share/virtualenv)
    added seed packages: pip==25.0.1, setuptools==75.3.2, wheel==0.45.1
  activators BashActivator,CShellActivator,FishActivator,NushellActivator,PowerShellActivator,PythonActivator
p$ (master *) . venv-vext/bin/activate
(venv-vext) p$ (master *) pip install vext
Collecting vext
  Using cached vext-0.7.6-py3-none-any.whl
Collecting ruamel.yaml>=0.11.10 (from vext)
  Using cached ruamel.yaml-0.18.10-py3-none-any.whl.metadata (23 kB)
Collecting ruamel.yaml.clib>=0.2.7 (from ruamel.yaml>=0.11.10->vext)
  Using cached ruamel.yaml.clib-0.2.8-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl.metadata (2.2 kB)
Using cached ruamel.yaml-0.18.10-py3-none-any.whl (117 kB)
Using cached ruamel.yaml.clib-0.2.8-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.whl (596 kB)
Installing collected packages: ruamel.yaml.clib, ruamel.yaml, vext
Successfully installed ruamel.yaml-0.18.10 ruamel.yaml.clib-0.2.8 vext-0.7.6
(venv-vext) p$ (master *) pip install -r requirements.txt 
Collecting ewmh (from -r requirements.txt (line 1))
  Using cached ewmh-0.1.6-py3-none-any.whl
Collecting pylint (from -r requirements.txt (line 8))
  Using cached pylint-3.2.7-py3-none-any.whl.metadata (12 kB)
Collecting pylint-pytest (from -r requirements.txt (line 9))
  Using cached pylint_pytest-1.1.8-py3-none-any.whl.metadata (6.0 kB)
Collecting pytest (from -r requirements.txt (line 11))
  Using cached pytest-8.3.5-py3-none-any.whl.metadata (7.6 kB)
Collecting pytest-cov (from -r requirements.txt (line 12))
  Using cached pytest_cov-5.0.0-py3-none-any.whl.metadata (27 kB)
Collecting python-xlib (from ewmh->-r requirements.txt (line 1))
  Using cached python_xlib-0.33-py2.py3-none-any.whl.metadata (6.2 kB)
Collecting platformdirs>=2.2.0 (from pylint->-r requirements.txt (line 8))
  Using cached platformdirs-4.3.6-py3-none-any.whl.metadata (11 kB)
Collecting astroid<=3.3.0-dev0,>=3.2.4 (from pylint->-r requirements.txt (line 8))
  Using cached astroid-3.2.4-py3-none-any.whl.metadata (4.5 kB)
Collecting isort!=5.13.0,<6,>=4.2.5 (from pylint->-r requirements.txt (line 8))
  Using cached isort-5.13.2-py3-none-any.whl.metadata (12 kB)
Collecting mccabe<0.8,>=0.6 (from pylint->-r requirements.txt (line 8))
  Using cached mccabe-0.7.0-py2.py3-none-any.whl.metadata (5.0 kB)
Collecting tomlkit>=0.10.1 (from pylint->-r requirements.txt (line 8))
  Using cached tomlkit-0.13.2-py3-none-any.whl.metadata (2.7 kB)
Collecting typing-extensions>=3.10.0 (from pylint->-r requirements.txt (line 8))
  Using cached typing_extensions-4.13.2-py3-none-any.whl.metadata (3.0 kB)
Collecting dill>=0.2 (from pylint->-r requirements.txt (line 8))
  Using cached dill-0.4.0-py3-none-any.whl.metadata (10 kB)
Collecting tomli>=1.1.0 (from pylint->-r requirements.txt (line 8))
  Using cached tomli-2.2.1-py3-none-any.whl.metadata (10 kB)
Collecting pytest (from -r requirements.txt (line 11))
  Using cached pytest-8.2.0-py3-none-any.whl.metadata (7.5 kB)
Collecting iniconfig (from pytest->-r requirements.txt (line 11))
  Using cached iniconfig-2.1.0-py3-none-any.whl.metadata (2.7 kB)
Collecting packaging (from pytest->-r requirements.txt (line 11))
  Using cached packaging-25.0-py3-none-any.whl.metadata (3.3 kB)
Collecting pluggy<2.0,>=1.5 (from pytest->-r requirements.txt (line 11))
  Using cached pluggy-1.5.0-py3-none-any.whl.metadata (4.8 kB)
Collecting exceptiongroup>=1.0.0rc8 (from pytest->-r requirements.txt (line 11))
  Using cached exceptiongroup-1.2.2-py3-none-any.whl.metadata (6.6 kB)
Collecting coverage>=5.2.1 (from coverage[toml]>=5.2.1->pytest-cov->-r requirements.txt (line 12))
  Using cached coverage-7.6.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (8.3 kB)
Collecting six>=1.10.0 (from python-xlib->ewmh->-r requirements.txt (line 1))
  Using cached six-1.17.0-py2.py3-none-any.whl.metadata (1.7 kB)
Using cached pylint-3.2.7-py3-none-any.whl (519 kB)
Using cached pylint_pytest-1.1.8-py3-none-any.whl (10 kB)
Using cached pytest-8.2.0-py3-none-any.whl (339 kB)
Using cached pytest_cov-5.0.0-py3-none-any.whl (21 kB)
Using cached astroid-3.2.4-py3-none-any.whl (276 kB)
Using cached coverage-7.6.1-cp38-cp38-manylinux_2_5_x86_64.manylinux1_x86_64.manylinux_2_17_x86_64.manylinux2014_x86_64.whl (235 kB)
Using cached dill-0.4.0-py3-none-any.whl (119 kB)
Using cached exceptiongroup-1.2.2-py3-none-any.whl (16 kB)
Using cached isort-5.13.2-py3-none-any.whl (92 kB)
Using cached mccabe-0.7.0-py2.py3-none-any.whl (7.3 kB)
Using cached platformdirs-4.3.6-py3-none-any.whl (18 kB)
Using cached pluggy-1.5.0-py3-none-any.whl (20 kB)
Using cached tomli-2.2.1-py3-none-any.whl (14 kB)
Using cached tomlkit-0.13.2-py3-none-any.whl (37 kB)
Using cached typing_extensions-4.13.2-py3-none-any.whl (45 kB)
Using cached iniconfig-2.1.0-py3-none-any.whl (6.0 kB)
Using cached packaging-25.0-py3-none-any.whl (66 kB)
Using cached python_xlib-0.33-py2.py3-none-any.whl (182 kB)
Using cached six-1.17.0-py2.py3-none-any.whl (11 kB)
Installing collected packages: typing-extensions, tomlkit, tomli, six, pluggy, platformdirs, packaging, mccabe, isort, iniconfig, exceptiongroup, dill, coverage, python-xlib, pytest, astroid, pytest-cov, pylint, ewmh, pylint-pytest
Successfully installed astroid-3.2.4 coverage-7.6.1 dill-0.4.0 ewmh-0.1.6 exceptiongroup-1.2.2 iniconfig-2.1.0 isort-5.13.2 mccabe-0.7.0 packaging-25.0 platformdirs-4.3.6 pluggy-1.5.0 pylint-3.2.7 pylint-pytest-1.1.8 pytest-8.2.0 pytest-cov-5.0.0 python-xlib-0.33 six-1.17.0 tomli-2.2.1 tomlkit-0.13.2 typing-extensions-4.13.2
(venv-vext) p$ (master *) pip install -e .
Obtaining file:///./p
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Building wheels for collected packages: auto-arrange
  Building editable for auto-arrange (pyproject.toml) ... done
  Created wheel for auto-arrange: filename=auto_arrange-0.1.0-0.editable-py3-none-any.whl size=1822 sha256=d144af95375a251961d90c1e501bdb07e17098304914262af63849fa949430ba
  Stored in directory: /tmp/pip-ephem-wheel-cache-f863nrxu/wheels/7d/1e/19/1e0bd49bcbe8f219f0190aadf4cdb572b765873834fc9da425
Successfully built auto-arrange
Installing collected packages: auto-arrange
Successfully installed auto-arrange-0.1.0
(venv-vext) p$ (master *) auto
auto-arrange   autoconf       autoflake      autoheader     autoimport     autom4te       automake@      automake-1.16  autoreconf     autoscan       autoupdate     
(venv-vext) p$ (master *) auto-arrange 
Traceback (most recent call last):
  File "p/venv-vext/bin/auto-arrange", line 5, in <module>
    from main import main
  File "p/src/main.py", line 13, in <module>
    import gi
ModuleNotFoundError: No module named 'gi'
$ head -n20 src/main.py 
#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections.abc import Iterator
from dataclasses import dataclass
from typing import Any, Dict, List

import gi
from ewmh import EWMH

# deps: python3-gi
gi.require_version("Gdk", "3.0")
from gi.repository import (  # noqa: E402 # pylint: disable=wrong-import-position # gi.require_version is a good safeguard
    Gdk,
)
$
```

**Comment by stuaxo** [comment]
Can you try ```vext -c '*'``` and paste the output ?

**Comment by stdedos** [comment]
```console
(venv-vext) p$ (master *) vext -c '*'
import gi.repository: [failed]

(venv-vext) p$ (master *) 
```

**Comment by stdedos** [comment]
_btw - I had to update my 20.04 / py3.8, as it went EOL_ 🙃
