### ISSUE TITLE
vext.gi doesn't work with Python 3.10

### ISSUE THREAD

**Issue by nathanael-naeri** [stuaxo/vext#89]
In a virtual environment created with Python 3.10 (`python3.10 -m venv my-venv`) and initialized with up-to-date versions of pip, setuptools, and wheel (`python3.10 -m pip install --upgrade pip setuptools wheel` - wheel necessary as per #84), plus `vext` and `vext.gi` of course, running `vext --check gi.vext` fails even though vext is enabled according to `vext --status`:

```
(my-venv) $ vext --status
Running in virtualenv [enabled]
(my-venv) $ vext --check gi.vext
import gi.repository: [failed]
```

This was not the case with Python 3.8 (and I didn't try 3.9).

Full traceback below:

```
(my-venv) $ python3
Python 3.10.8 (main, Oct 12 2022, 19:14:26) [GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import gi.repository
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/me/my-venv/lib/python3.10/site-packages/vext/gatekeeper/__init__.py", line 209, in load_module
    module = imp.load_module(name, *self.module_info)
  File "/usr/lib/python3.10/imp.py", line 245, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.10/imp.py", line 217, in load_package
    return _load(spec)
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
```

Sadly I am unable to fix this issue.

**Comment by stuaxo** [comment]
Interesting, and can you confirm pygobject works in the system python3.10

**Comment by nathanael-naeri** [comment]
Good call: it does not, and the reason might have something to do with the fact that my system Python 3.10 is provided by the [deadsnakes PPA](https://launchpad.net/~deadsnakes/+archive/ubuntu/ppa) on an Ubuntu 20.04 LTS system where the default system Python is 3.8.

```
$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[...]
>>> import gi.repository

$ python3.10
Python 3.10.8 (main, Oct 12 2022, 19:14:26)
[...]
>>> import gi.repository
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: cannot import name '_gi' from partially initialized module 'gi' (most likely due to a circular import) (/usr/lib/python3/dist-packages/gi/__init__.py)
```

No idea how to fix that, but in any case, not caused by `vext`, so we can close this issue.

**Comment by nathanael-naeri** [comment]
> No idea how to fix that

Old StackOverflow posts hint at creating 3.10 symlinks to the 3.8 shared libraries of _gi and _gi_cairo in the system's Python installation:

```
cd /usr/lib/python3/dist-packages/gi
sudo ln -s _gi_cairo.cpython-38-x86_64-linux-gnu.so _gi_cairo.cpython-310-x86_64-linux-gnu.so
sudo ln -s _gi.cpython-38-x86_64-linux-gnu.so _gi.cpython-310-x86_64-linux-gnu.so
```

But (unsurprisingly) this doesn't work, probably because the fake 3.10 libraries created that way are not the expected actual 3.10 ones:

```
$ python3.10
Python 3.10.8 (main, Oct 12 2022, 19:14:26)
[...]
>>> import gi.repository
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3/dist-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib/python3/dist-packages/gi/_gi.cpython-310-x86_64-linux-gnu.so: undefined symbol: _PyTraceMalloc_NewReference
```

**Comment by stuaxo** [comment]
Yeah if you are linking from a library in a virtual env (with symlinks or vext) to a system Python, they have to be exactly the same build.

A virtualenv with system-site-packages might be something you can try falling back to.

**Comment by nathanael-naeri** [comment]
Makes sense. A virtual environment with system-site-packages would work indeed, although I was trying to avoid that.

Closing this issue now, as it is not an issue with `vext` after all.
